#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: f032afc
#
Name     : R-RhpcBLASctl
Version  : 0.23.42
Release  : 1
URL      : https://cran.r-project.org/src/contrib/RhpcBLASctl_0.23-42.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RhpcBLASctl_0.23-42.tar.gz
Summary  : Control the Number of Threads on 'BLAS'
Group    : Development/Tools
License  : AGPL-3.0
Requires: R-RhpcBLASctl-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
And possible to control the number of threads in 'OpenMP'.
  Get a number of logical cores and physical cores if feasible.

%package lib
Summary: lib components for the R-RhpcBLASctl package.
Group: Libraries

%description lib
lib components for the R-RhpcBLASctl package.


%prep
%setup -q -n RhpcBLASctl

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697645040

%install
export SOURCE_DATE_EPOCH=1697645040
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RhpcBLASctl/DESCRIPTION
/usr/lib64/R/library/RhpcBLASctl/INDEX
/usr/lib64/R/library/RhpcBLASctl/Meta/Rd.rds
/usr/lib64/R/library/RhpcBLASctl/Meta/features.rds
/usr/lib64/R/library/RhpcBLASctl/Meta/hsearch.rds
/usr/lib64/R/library/RhpcBLASctl/Meta/links.rds
/usr/lib64/R/library/RhpcBLASctl/Meta/nsInfo.rds
/usr/lib64/R/library/RhpcBLASctl/Meta/package.rds
/usr/lib64/R/library/RhpcBLASctl/NAMESPACE
/usr/lib64/R/library/RhpcBLASctl/R/RhpcBLASctl
/usr/lib64/R/library/RhpcBLASctl/R/RhpcBLASctl.rdb
/usr/lib64/R/library/RhpcBLASctl/R/RhpcBLASctl.rdx
/usr/lib64/R/library/RhpcBLASctl/help/AnIndex
/usr/lib64/R/library/RhpcBLASctl/help/RhpcBLASctl.rdb
/usr/lib64/R/library/RhpcBLASctl/help/RhpcBLASctl.rdx
/usr/lib64/R/library/RhpcBLASctl/help/aliases.rds
/usr/lib64/R/library/RhpcBLASctl/help/paths.rds
/usr/lib64/R/library/RhpcBLASctl/html/00Index.html
/usr/lib64/R/library/RhpcBLASctl/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/RhpcBLASctl/libs/RhpcBLASctl.so
/usr/lib64/R/library/RhpcBLASctl/libs/RhpcBLASctl.so.avx2
/usr/lib64/R/library/RhpcBLASctl/libs/RhpcBLASctl.so.avx512
